title: Petr³
description: Documentation website for Petr³
theme: just-the-docs

url: https://cubic-petr-bot.github.io

aux_links:
  
footer_content: "&copy; Copyright Rubik's Cube Club @ UCI. All Rights Reserved."